### ISSUE TITLE
Kill VEL when Smite dies

### ISSUE THREAD

**Issue by cyoung502** [cyoung502/VEL#3]
Make VEL die when Smite dies.

**Comment by mbeaver502** [comment]
Worth looking at? [psutil.wait_procs](https://psutil.readthedocs.io/en/latest/#psutil.wait_procs)

> Convenience function which waits for a list of Process instances to terminate. Return a (gone, alive) tuple indicating which processes are gone and which ones are still alive. 

```python
import psutil

def on_terminate(proc):
    print("process {} terminated with exit code {}".format(proc, proc.returncode))

procs = psutil.Process().children()
for p in procs:
    p.terminate()
gone, alive = psutil.wait_procs(procs, timeout=3, callback=on_terminate)
for p in alive:
    p.kill()
```
Also for consideration: [Process.is_running](https://psutil.readthedocs.io/en/latest/#psutil.Process.is_running) and [Process.wait](https://psutil.readthedocs.io/en/latest/#psutil.Process.wait).

**Comment by cyoung502** [comment]
Added in v1.2
